import type { Metadata } from "next";
import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import {menu} from "../app/menu/page"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import { Sidebar } from "@/components/sidebar/sidebar";
import { ClientRouteManager } from "@/components/ClientRouteManager";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Serve Fixe - Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   
  return (
    <ClerkProvider >
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          geistMono.className
        )}
      >
          <SignedIn>
            <Sidebar />
            <nav className="sm:ml-14 p-4">
              {children}
            </nav>
            
          </SignedIn>
          
          <SignedOut>
            <RedirectToSignIn/>
          </SignedOut>
          <menu/>
       </body>
      </html>
      </ClerkProvider>
  );
}
